import type { Metadata } from 'next'
import '../styles/_colors.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='h-screen flex items-center justify-center bg-black text-white dark:bg-black dark:text-white'>{children}</body>
    </html>
  )
}
